#! /bin/sh

############
# Monitors #
############
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 # Ten monitors, arabics numbers.


###################
# Gaps and border #
###################
bspc config border_width         2 # Width of the borders
bspc config window_gap          15 # Gap between the windows
bspc config normal_border_color "#575976" # Grey color
bspc config focused_border_color "#007A01" # Green color
bspc config presel_feedback_color "#26396D" # Blue color


######################
# Some others things #
######################
bspc config split_ratio          0.50 # Split ratio (1/2)
bspc config borderless_monocle   false # Add borders when there is a monocle
bspc config gapless_monocle      true # Remove the gaps when it's monocle mod
bspc config focus_follows_pointer true # The cursor auto-focus the window under


#########
# Rules #
#########
bspc rule -a URxvt state=floating # URxvt spawn floating
bspc rule -a floating state=floating
bspc rule -a Gpick state=floating # Gpick spawm floating
bspc rule -a mpv state=floating # mpv spawn floating
bspc rule -a Orage state=floating # Spawn orage floating
bspc rule -a Pavucontrol state=floating # Spawn Pulseaudio control panel floating
bspc rule -a Pdf2png state=floating # Spawn Pdf2png floating
bspc rule -a minecraft-launcher state=pseudo_tiled # Spawn Minecraft Launcher floating
bspc rule -a hakuneko-desktop state=floating # Spawn manga downloader floating

bspc rule -a Gimp desktop='^8' state=floating follow=on # Gimp spawn floating on desktop 8 (and follow it)
bspc rule -a inkscape desktop='^8' follow=on # Inkscape spawn floating on desktop 8

bspc rule -a discord desktop='^2' follow=false # Discord spawn on desktop 2
bspc rule -a Sxiv state=floating


#############
# Autostart #
#############
$HOME/.config/bspwm/autostart.sh # All programs to start
