#!/bin/bash

WAL=$(tail -n 1 ~/.fehbg | sed 's/feh\ --no-fehbg\ --bg-fill\ //')
echo $WAL | xargs wal -i && dunstify --urgency=normal --icon=preferences-wallpaper "Pywal" "Theme updated according the wallpaper you are using"
