#!/bin/fish

set -l wal (tail --lines 1 $WALLPAPER/.wall-list | sed 's/wallpaper/wal\ -i\ $WALLPAPER\/wallpaper/')
fish -c $wal
systemctl --user restart dunst
dunstify --urgency=normal --icon=preferences-wallpaper "Pywal" "Theme updated according the wallpaper you are using"
