#!/bin/sh
# opout: "open output": A general handler for opening a file's intended output.
# I find this useful especially running from vim.
# Thanks Luke Smith

basename="$(echo "$1" | sed 's/\.[^\/.]*$//')"
READER="$(zathura)"
BROWSER="surf"

case "$1" in
	*.tex|*.md|*.rmd|*.ms|*.me|*.mom) setsid "zathura" "$basename".pdf >/dev/null 2>&1 & ;;
	*.html|*.Rmd) setsid "$BROWSER" "$basename".html >/dev/null 2>&1 & ;;
	*.sent) setsid sent "$1" >/dev/null 2>&1 & ;;
esac
