#!/bin/fish

function pc_shutdown
	/home/luc/bin/control/mpd-control shutdown
	systemctl -i poweroff
end



set -l menu (echo " Lock| Logout| Reboot| Shutdown" | rofi -sep "|" -dmenu -i -p 'System' -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 | head --lines=1 )

switch $menu
	case '*Lock'
		i3lock-fancy
	case '*Logout'
		bspc quit
	case '*Reboot'
		systemctl reboot
	case '*Shutdown'
		pc_shutdown
end
