#!/bin/bash

cd Documents/Liste/source/

MENU="dmenu -l 3 -p "Doing?""
DOING=$(echo -e "Edit : Open a terminal and edit The List\nCompile : Open a terminal and compile The List\nOpen : Open the list with surf" | $MENU)

Edit() {
	EditMenu="dmenu -l 7 -p "Which?""
	place=$(echo -e "Index : Ouvrir l'index\nLivres : Ouvrir le liste de livres\nDocumentaires : Ouvrir la liste documentaires\nFilms : Ouvrir la liste films\nSéries : Ouvrir la liste Séries\nSéries Audios : Ouvrir la liste Séries Audios\nAutres : Ouvrir la liste Autres" | $EditMenu)
	case "$place" in
		Index*) st -e nvim index.Rmd ;;
		Livres*) st -e nvim livres.Rmd ;;
		Documentaires*) st -e nvim documentaires.Rmd ;;
		Films*) st -e nvim films.Rmd ;;
		"Séries :"*) st -e nvim series.Rmd ;;
		"Séries Audios"*) st -e nvim series_audios.Rmd ;;
		Autres*) st -e nvim autres.Rmd ;;
		*) exit 1
	esac
}

case "$DOING" in
	Edit*) Edit ;;
	Compile*) urxvt -e sh -c 'cd ../ && ./render.sh && echo -e "\nPress [Enter] to close" && read' ;;
	Open*) surf ../site/index.html ;;
	*) exit 1
esac
